### ISSUE TITLE
Missing About

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/dp-420-cosmos-db-dev.zh-CN#18]
Missing the information in "About" field.

Missing the Link to "Github Pages"
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/64255878/157817350-dd93aa55-b0b1-4376-8a84-0594b7da4909.png)

**Comment by stonezy123** [comment]
not loclization issue

**Comment by olprod** [comment]
![image](https://user-images.githubusercontent.com/16075726/184617701-9a279c24-3c89-4bd0-8b34-71f1ee7cf6d0.png)
