### ISSUE TITLE
03-migrate-data.md - extra bold tag present

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/dp-420-cosmos-db-dev.zh-CN#21]
In this doc, in the first Task, Step 21, there are two extra bold tags at the end:

选择“缩放和设置”节点。 在“缩放和设置”选项卡中，选择“手动”，将“所需吞吐量”设置从“4000 RU/秒”更新为“400 RU/秒”，然后保存更改**。

**Comment by chriscarty00** [comment]
[Locfiles](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPlRydWU8L1NBVE8%2bPFNBTE8%2bRmFsc2U8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7V1dMPC9RUj48UVIgSWQ9IjIiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0xvY0ZpbGVzO0xhbmd1YWdlO0VxdWFsO0NoaW5lc2UgKFNpbXBsaWZpZWQpPC9RUj48UVIgSWQ9IjMiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgQXNzZXQgSUQ7RXF1YWw7MDMtbWlncmF0ZS1kYXRhLm1kPC9RUj48L1FUPjxSRz48R0M%2bTlVMTDwvR0M%2bPC9SRz48L1ZQUT4%3d) to update

**Comment by chriscarty00** [comment]
Update made and locfile uploaded
