### ISSUE TITLE
15-cognitive-search.md - extra bold tag present

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/dp-420-cosmos-db-dev.zh-CN#22]
In this doc, in the Task 'Azure Cosmos DB for NoSQL 数据的生成索引器和索引', in the Table for Step 3, there are two extra bold tags at the end:

之前创建的 Azure Cosmos DB for NoSQL 帐户的连接字符串**

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
[Locfiles ](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPlRydWU8L1NBVE8%2bPFNBTE8%2bRmFsc2U8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7V1dMPC9RUj48UVIgSWQ9IjIiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0xvY0ZpbGVzO0xhbmd1YWdlO0VxdWFsO0NoaW5lc2UgKFNpbXBsaWZpZWQpPC9RUj48UVIgSWQ9IjMiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgQXNzZXQgSUQ7RXF1YWw7MTUtY29nbml0aXZlLXNlYXJjaC5tZDwvUVI%2bPC9RVD48Ukc%2bPEdDPk5VTEw8L0dDPjwvUkc%2bPC9WUFE%2b)to update

**Comment by chriscarty00** [comment]
Update made and locfile uploaded
